const nomeUsuario = prompt("Qual é o seu nome ?")
const comida1 = prompt("Qual a sua comida favorita?")
const comida2 = prompt("Qual a sua segunda comida favorita?")
const coomida3 = prompt("Qual a sua terceira comida favorita?")
console.log(`essas são as 3 comidas de ${nomeUsuario} \n -${comida1} \n -${comida2} \n -${coomida3}`)